version: '3.9'

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PORT: ${PG_PORT}

